databases:
  mysql_oyunzor_survival:
    type: mysql
    host: mysql
    port: 3306
    database: oyunzor_survival
    username: oyunzor
    password: ozlocaldev123

  clickhouse_log:
    type: clickhouse
    host: clickhouse
    port: 8123
    database: oyunzor_global
    username: oyunzor
    password: ozlocaldev123

  hazelcast_cache:
    type: hazelcast
    address: localhost
    port: 5701
    cluster-name: oyunzor-survival
